### PR TITLE
Update cursor

### PR DESCRIPTION
**Pull request by TheExpertNoob**
The circle is so last decade. Lets go a few decades back with a Mario Hand cursor!

### CODE REVIEW

**Comment by TheExpertNoob** [comment]
image
Preview. Finger SHOULD be touch point in the graphic (center of image?)

**Comment by impeeza** [comment]
Let's make it not only for a day, the other which appears only for a day can stand.

**Comment by CTCaer** [comment]
squaresoft and snes capcom cursors are better

**Comment by TheExpertNoob** [comment]
nyx20250221_181508
Its really not that bad.

**Pull request closed without merging**
