### PR TITLE
hos: add HOS 16.0.0 support

### PR DESCRIPTION
**Pull request by Steveice10**
Added support for 16.0.0 based on the 15.0.0 changes. emuMMC patch updates are based on the corresponding Atmosphere patch updates, and key updates are based on the corresponding Lockpick_RCM updates.

Have not tested emuMMC but stock sysMMC boots perfectly fine in my testing. Would appreciate verification I didn't miss or do anything incorrectly here. Until then use at your own risk.

### CODE REVIEW

**Comment by ProxyThaGod** [comment]
how do i download the new version?

**Review by Nerdvsmoles — APPROVED** [review]

**Comment by CTCaer** [comment]
Thanks for the effort but that was already done. I never release hekate when atmosphere needs updating also.
Otherwise there will be a flood of users reporting yellow screens.

Ofc if atmosphere gets a release at a weird time (timezone wise), that's another story.

Since, you know what to update (your PR is lgtm, except 1 thing), in the future you should know that there are no emuMMC patches. So dunno what you are referring there.
So after updating the relevant new master key stuff, the emuMMC kipm is compiled based on https://github.com/m4xw/emuMMC and you just drag n drop it in its predefined directory.

**Comment by Steveice10** [comment]
Ah okay, good to know for the future. Just figured that since I'd done it myself locally I might as well PR in case it might be useful to save some work.

For emuMMC patches I was referring to the FS patches in pkg2_patches, but I guess I got the exact purpose of those wrong. For my local testing I did go to that other repo and compile it as I noticed that file wasn't produced by the hekate build.

**Comment by Solljak** [comment]
> 

Hi, 

I doing something wrong, because im getting a yellow screen that you mentioned. 
Is there an idiots guide to where im going wrong?

**Pull request closed without merging**
