### PR TITLE
Added some more icons.

### PR DESCRIPTION
**Pull request by NicholeMattera**
I created some more icons yesterday, and I wasn't sure if you wanted to include them or not in the next release:

- **icon_android** - For switchroot LineageOS.
- **icon_atmosphere** - For chainloading Fusée.
- **icon_linux** - For distros other than L4T Ubuntu.
- **icon_lockpick** - For chainloading Lockpick RCM.
- **icon_ubuntu** - For L4T Ubuntu.

I also made sure all the icons are consistently sized to fit within 160x160 and then increased the canvas size to 192x192. This should make the icons more consistent. (I think only icon_payload was larger than 160x160 before.) All the icons come with hue versions, and I made a custom version of icon_switch, however I didn't include that in this pull request. I've also put all the vector art and project files up here: https://github.com/NicholeMattera/Hekate-Icons

image

image

### CODE REVIEW

**Comment by CTCaer** [comment]
Hi, thanks for the PR.

Is it possible to make icons for arch and gentoo? (These are also working switch distros)
Also rename to `icon_lockpick.bmp` to `Lockpick_RCM.bmp` so the automatic icon assignment works with the released payload.

Also why the payload/switch icons changed? Have in mind that I did normalize them. Not based on pixels, but on perceived size. (Haven't checked how the new ones look though. Will do later)

**Comment by NicholeMattera** [comment]
Sure I can make icons for both arch and gentoo as well. I'm currently working though, so it will be a few hours before I can get around to creating them. I don't think the switch icon changed at all I just copied the one I had from my repo. The payload icon shrunk just a tad. (I'm using the none hue variant to just show the change below. The hue version is being used in the PR.)

image

**Comment by CTCaer** [comment]
Yeah just checked them on real hw. The perceived size now feels smaller than the switch icon.
So it's better to not change it. Also please remove the change from the switch icon so the PR is clean.

As for the atmosphere icon, the usage is split. So it's preferable to stay as is and be done by the user.

Generally, I don't want to ship icons or force users on specific ones.
And certainly I don't want to convert a hekate release to a giant theme pack.
Not even the Lakka icon has a place here to be frank.
Also don't forget that the release is supposed to be copy paste compatible.

Anyway, let me think about it though.

PS: Whatever the outcome of this PR, I would still like to send the l4t icons to the maintainers for a possible inclusion in the switchroot official release archives.

**Comment by NicholeMattera** [comment]
I've reverted both the switch and payload icons.

That makes perfect sense about not wanting to ship icons. I just wanted to offer these as I knew the Lakka icon was included, and I wasn't sure if you wanted to include some more. :wink:

**Comment by skalfate** [comment]
Thank you @NicholeMattera , for the beautiful icons. I will definitely be using them. If I may suggest to @CTCaer CTCaer, the pack can be used as an additional download right on release section. That Art will visualize your magic, just like nyx 9.0 did.

**Comment by CTCaer** [comment]
So I decided to not clutter the repo and release with icons.
I also removed the Lakka icon and its hardcoded references.

Also sections can now search for a normal icon and then for a hue icon, if normal not found.

As the only source of hue icons and also their creator, I added a link to release.
As for the L4T icons, I will send them to the relevant parties. Thanks

**Pull request closed without merging**
