### PR TITLE
Update and rename hekate_ipl_template.ini to hekate_ipl.ini

### PR DESCRIPTION
**Pull request by NotErista**

### CODE REVIEW

**Comment by impeeza** [comment]
I do not understand the purpose of this change. Is supposed you manually copy the template to you needed ini file.

**Comment by masagrator** [comment]
template is there so it would not overwrite accidentally config when you will update hekate. 
You missed the whole point of template and not including original name.

**Comment by NotErista** [comment]
Sorry I thought I forked this

**Comment by CTCaer** [comment]
Template is for eyeballing it and copy pasting and changing entries. Not to be used as is.

The whole section down in the template tells you that.
(And the readme)

**Pull request closed without merging**
