### PR TITLE
Allow disabling built-in custom splash

### PR DESCRIPTION
**Pull request by aveao**
This PR adds a simple define that allows disabling the built-in custom splash, so that the size of Hekate can be reduced even further when needed (during development, for payload injectors with limited amount of flash storage etc).

The current dev branch is 126117 bytes, with menu logo removed it gets down to 118221 bytes (saving 7896 bytes), and with splash removed in addition to that (which this PR allows), it gets down to 111381 bytes (saving 6840 bytes).

### CODE REVIEW

**Comment by CTCaer** [comment]
Thank you for the PR.

That's welcomed, but unfortunately not needed.
After the new release, more and more things will leave hekate's nest and go to sd card.
Because I don't have a lot of time, for now only lp0 is out. Which makes the binary 115997 (this includes all features that'll come, otherwise it's 110KB).

If you want an easy way or switch for testing, you can just comment Tools and Console info.
Also there's no need to make switches everywhere for a dev test. You can comment the usages. 
Objdump will strip everything else.

**Comment by aveao** [comment]
I do understand that commenting tools and console info will help with reducing size, but simply disabling logos allows saving space without losing any functionality (unlike commenting out those two), making it a valid candidate for production environments with limited space available to them (such as future payload injectors that may be based on ATSAMD21G17 [which is %28 cheaper than the G18], which only has 128KB of flash).

Having an easy way to switch off the splash also makes it easier to build Hekate with reduced size on a CI environment. While a diff would also work, they're painful to create (a diff made with `git diff` can work on one environment and not on another etc) and tend to cause issues than simply using sed to remove `-DSPLASH_ENABLE` from Makefile.

In addition to this, the menu logo already has a switch, so it makes sense for the splash (the only other logo) to have one too.

**Comment by m4xw** [comment]
Or you know, you could apply compression algorithms, thin out the code by yourself or use modules which will be released soon.
There is literally 0 reason to remove the logo as of now.
If you cheap out on the used chip add some kind of memory already.
And its not like CI/CD would make it "harder" with the logo, actually i beg to differ on this.
Just fork it already if u really want those changes.

**Comment by aveao** [comment]
I fucking hate this scene.

**Comment by m4xw** [comment]
> You're a very professional and mature member of the switch scene.
Well I can say the same about you after that little rant.

Anyway:
Your changes are already obsolete on my and ctc's dev branches for various reasons.

Patience will pay off.

**Comment by CTCaer** [comment]
@m4xw

**Pull request closed without merging**
