### PR TITLE
Fix debug uart

### PR DESCRIPTION
**Pull request by hyln9**
Fix debug uart output for uart-b/c by switching its pin from GPIO mode to the default SPIO (SFIO) if required.
Fix misplaced TX/RX configuration in "pinmux_config_uart" function.
Rewrite "uart.c" based on "UART Programming Guidelines" of Tegra X1 TRM and uart input now works.
Add "DEBUG_UART_PORT" macro for convenience.

### CODE REVIEW

**Comment by hyln9** [comment]
Actually I don't know why hwinit originally initialize those joycon pins as GPIO because joycon works fine for me without that.

**Comment by CTCaer** [comment]
The changes seem good.

The reason is that ninty's bootloader configures them like this.
Internally we change them to debug.

**Comment by hyln9** [comment]
Oh I see. Btw, uart input seems broken too, and I'll submit another change soon.

**Comment by hyln9** [comment]
Pushed.

**Comment by CTCaer** [comment]
I'll test it when I can and come back to you

**Comment by CTCaer** [comment]
Thank you for the PR.
It works splendidly

**Pull request merged**
