### PR TITLE
Landscape

### PR DESCRIPTION
**Pull request by balika011**

### CODE REVIEW

**Comment by CTCaer** [comment]
Thank you for your PR.

Have in mind that I'll need some time to review, as I didn't have time, because of i2c/touchscreen/gui fixes.

**Comment by CTCaer** [comment]
Tested perf. Too slow.

I'm already working on a solution though. (HWimage rotation).

**Comment by HookedBehemoth** [comment]
Is this superseeded by NYX?

**Comment by fennectech** [comment]
Perhaps.  Perhaps not.

**Comment by CTCaer** [comment]
A faster and proper implementation that can be used as reference is in Nyx, that also supports 2 columns (auto-based).

**Pull request closed without merging**
